version: "3.4"

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: webapi/Dockerfile
    ports:
      - "443:443"
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: HousingReservation
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  reactapp:
    image: ${DOCKER_REGISTRY-}reactapp
    build:
      context: ../reactapp
      dockerfile: Dockerfile
    ports:
      - "80:3000"  
    depends_on:
      - webapi
volumes:
  postgres-data:  
