// <auto-generated />
using System;
using HousingReservation.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ReservationDbContext))]
    [Migration("20231108125953_SanatoriumContacts")]
    partial class SanatoriumContacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SanatoriumId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TourAgencyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SanatoriumId");

                    b.HasIndex("TourAgencyId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Domain.Entities.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRefreshTokens");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.Attribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttributeGroupId");

                    b.HasIndex("RoomId");

                    b.ToTable("Attributes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d57717f-4f93-48d1-b10c-60f39bb3661a"),
                            AttributeGroupId = new Guid("052a9517-ad4a-4452-8df4-ea64748feb41"),
                            DateCreated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "Кондиционер",
                            IsActive = false
                        },
                        new
                        {
                            Id = new Guid("adb984ce-ef40-4827-92f4-093b9d61d0bf"),
                            AttributeGroupId = new Guid("052a9517-ad4a-4452-8df4-ea64748feb41"),
                            DateCreated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "Обогреватель",
                            IsActive = false
                        },
                        new
                        {
                            Id = new Guid("19783aae-27ca-4c3f-9ab6-b1845a17841f"),
                            AttributeGroupId = new Guid("052a9517-ad4a-4452-8df4-ea64748feb41"),
                            DateCreated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "Утюг",
                            IsActive = false
                        },
                        new
                        {
                            Id = new Guid("f2329d6c-df67-48d3-bbd9-b1b66da8b4d6"),
                            AttributeGroupId = new Guid("052a9517-ad4a-4452-8df4-ea64748feb41"),
                            DateCreated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "Гладильная доска",
                            IsActive = false
                        },
                        new
                        {
                            Id = new Guid("acf1a40f-1330-4923-abe3-536ae59a13a0"),
                            AttributeGroupId = new Guid("052a9517-ad4a-4452-8df4-ea64748feb41"),
                            DateCreated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "Телевизор",
                            IsActive = false
                        },
                        new
                        {
                            Id = new Guid("17829280-b63e-4be4-822c-165913d955ee"),
                            AttributeGroupId = new Guid("052a9517-ad4a-4452-8df4-ea64748feb41"),
                            DateCreated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "Фен",
                            IsActive = false
                        },
                        new
                        {
                            Id = new Guid("b5252812-8ce8-446c-8b25-688b0e8cab2e"),
                            AttributeGroupId = new Guid("3dd3f802-e622-45af-9272-3db75d662385"),
                            DateCreated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "Wi-Fi",
                            IsActive = false
                        },
                        new
                        {
                            Id = new Guid("e9786557-4633-4b9a-bf99-24e2be984645"),
                            AttributeGroupId = new Guid("3dd3f802-e622-45af-9272-3db75d662385"),
                            DateCreated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "Сауна",
                            IsActive = false
                        },
                        new
                        {
                            Id = new Guid("1b6f466d-06f0-4390-9499-aeec8bb91fef"),
                            AttributeGroupId = new Guid("3dd3f802-e622-45af-9272-3db75d662385"),
                            DateCreated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "Спортзал",
                            IsActive = false
                        },
                        new
                        {
                            Id = new Guid("8d48a314-a296-43b3-90fc-0e3cf8e1f301"),
                            AttributeGroupId = new Guid("3dd3f802-e622-45af-9272-3db75d662385"),
                            DateCreated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "Бассейн без подогрева",
                            IsActive = false
                        },
                        new
                        {
                            Id = new Guid("6815f25c-b2b7-45fd-93f1-93f7a90f9e91"),
                            AttributeGroupId = new Guid("5d4b064b-d6af-4a23-be3d-d3bd53ae7562"),
                            DateCreated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "Соляная пещера",
                            IsActive = false
                        },
                        new
                        {
                            Id = new Guid("e37fd658-9638-4b52-896f-481dac22ab45"),
                            AttributeGroupId = new Guid("5d4b064b-d6af-4a23-be3d-d3bd53ae7562"),
                            DateCreated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "Радоновые ванны",
                            IsActive = false
                        },
                        new
                        {
                            Id = new Guid("00fea9a2-111d-473b-bccc-41f017f2e518"),
                            AttributeGroupId = new Guid("5d4b064b-d6af-4a23-be3d-d3bd53ae7562"),
                            DateCreated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "Массаж",
                            IsActive = false
                        });
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.AttributeGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AttributeGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d4b064b-d6af-4a23-be3d-d3bd53ae7562"),
                            DateCreated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "Услуги",
                            IsActive = false,
                            Name = "Service"
                        },
                        new
                        {
                            Id = new Guid("3dd3f802-e622-45af-9272-3db75d662385"),
                            DateCreated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "Комфорт на территории",
                            IsActive = false,
                            Name = "SanatoriumComfort"
                        },
                        new
                        {
                            Id = new Guid("052a9517-ad4a-4452-8df4-ea64748feb41"),
                            DateCreated = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "Комфорт в номере",
                            IsActive = false,
                            Name = "RoomComfort"
                        });
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.BathroomType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BathroomTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("692ccc6f-4721-4946-8790-b31b6707d3d3"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 11, 8, 12, 59, 53, 58, DateTimeKind.Unspecified).AddTicks(8504), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "Отдельный",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("37d57656-b9ad-4c98-8063-b70183a88115"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 11, 8, 12, 59, 53, 58, DateTimeKind.Unspecified).AddTicks(8506), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "На территории санатория",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.MealType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MealTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2d484004-6682-4555-a2b5-15dc28da5a60"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 11, 8, 12, 59, 53, 58, DateTimeKind.Unspecified).AddTicks(8488), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "Отдельная",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("af4944ce-e920-4c83-86dd-4a078182a28d"),
                            DateCreated = new DateTimeOffset(new DateTime(2023, 11, 8, 12, 59, 53, 58, DateTimeKind.Unspecified).AddTicks(8490), new TimeSpan(0, 0, 0, 0, 0)),
                            FriendlyName = "На территории санатория",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SanatoriumId")
                        .HasColumnType("uuid");

                    b.Property<string>("SmallUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThumbUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TourAgencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TourId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SanatoriumId");

                    b.HasIndex("TourAgencyId");

                    b.HasIndex("TourId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.PromoBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PromoBlocks");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.PromoBlockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdminRequestStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DateAccepted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateCanceled")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Days")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PromoBlockId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SanatoriumId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TourAgencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TourId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PromoBlockId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SanatoriumId");

                    b.HasIndex("TourAgencyId");

                    b.HasIndex("TourId");

                    b.ToTable("PromoBlockItems");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.PromoRowItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdminRequestStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DateAccepted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateCanceled")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Days")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SanatoriumId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SanatoriumId");

                    b.ToTable("PromoRowItems");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccommodationRating")
                        .HasColumnType("integer");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntertainmentRating")
                        .HasColumnType("integer");

                    b.Property<int>("FoodRating")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LocationRating")
                        .HasColumnType("integer");

                    b.Property<int>("OverallRating")
                        .HasColumnType("integer");

                    b.Property<Guid>("SanatoriumId")
                        .HasColumnType("uuid");

                    b.Property<int>("StaffRating")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("SanatoriumId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BathroomTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("BedroomCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DoubleBedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MealTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("MinDaysReservation")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("numeric");

                    b.Property<int>("RoomType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SanatoriumId")
                        .HasColumnType("uuid");

                    b.Property<int>("SingleBedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BathroomTypeId");

                    b.HasIndex("GroupId");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("SanatoriumId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.RoomAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomAttributes");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.RoomGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RoomGroups");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.RoomReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GuestsCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("RoomReservations");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.Sanatorium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheckInTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CheckOutTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ObjectType")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Sanatoriums");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.SanatoriumAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SanatoriumId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("SanatoriumId");

                    b.ToTable("SanatoriumAttributes");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.SanatoriumPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SanatoriumId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("SanatoriumId");

                    b.ToTable("SanatoriumPlaces");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.Tour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.TourAgency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("TourAgencies");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.TourBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TourId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.HasIndex("UserId");

                    b.ToTable("TourBookings");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.Contact", b =>
                {
                    b.HasOne("HousingReservation.Domain.Entities.Sanatorium", "Sanatorium")
                        .WithMany("Contacts")
                        .HasForeignKey("SanatoriumId");

                    b.HasOne("HousingReservation.Domain.Entities.TourAgency", "TourAgency")
                        .WithMany("Contacts")
                        .HasForeignKey("TourAgencyId");

                    b.Navigation("Sanatorium");

                    b.Navigation("TourAgency");
                });

            modelBuilder.Entity("Domain.Entities.UserRefreshToken", b =>
                {
                    b.HasOne("HousingReservation.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.Attribute", b =>
                {
                    b.HasOne("HousingReservation.Domain.Entities.AttributeGroup", "AttributeGroup")
                        .WithMany("Attributes")
                        .HasForeignKey("AttributeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousingReservation.Domain.Entities.Room", null)
                        .WithMany("Attributes")
                        .HasForeignKey("RoomId");

                    b.Navigation("AttributeGroup");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.Photo", b =>
                {
                    b.HasOne("HousingReservation.Domain.Entities.Place", "Place")
                        .WithMany("Photos")
                        .HasForeignKey("PlaceId");

                    b.HasOne("HousingReservation.Domain.Entities.Room", "Room")
                        .WithMany("Photos")
                        .HasForeignKey("RoomId");

                    b.HasOne("HousingReservation.Domain.Entities.Sanatorium", "Sanatorium")
                        .WithMany("Photos")
                        .HasForeignKey("SanatoriumId");

                    b.HasOne("HousingReservation.Domain.Entities.TourAgency", "TourAgency")
                        .WithMany("Photos")
                        .HasForeignKey("TourAgencyId");

                    b.HasOne("HousingReservation.Domain.Entities.Tour", "Tour")
                        .WithMany("Photos")
                        .HasForeignKey("TourId");

                    b.Navigation("Place");

                    b.Navigation("Room");

                    b.Navigation("Sanatorium");

                    b.Navigation("Tour");

                    b.Navigation("TourAgency");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.PromoBlockItem", b =>
                {
                    b.HasOne("HousingReservation.Domain.Entities.PromoBlock", "PromoBlock")
                        .WithMany("PromoBlockItems")
                        .HasForeignKey("PromoBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousingReservation.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.HasOne("HousingReservation.Domain.Entities.Sanatorium", "Sanatorium")
                        .WithMany()
                        .HasForeignKey("SanatoriumId");

                    b.HasOne("HousingReservation.Domain.Entities.TourAgency", "TourAgency")
                        .WithMany()
                        .HasForeignKey("TourAgencyId");

                    b.HasOne("HousingReservation.Domain.Entities.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId");

                    b.Navigation("PromoBlock");

                    b.Navigation("Room");

                    b.Navigation("Sanatorium");

                    b.Navigation("Tour");

                    b.Navigation("TourAgency");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.PromoRowItem", b =>
                {
                    b.HasOne("HousingReservation.Domain.Entities.Sanatorium", "Sanatorium")
                        .WithMany()
                        .HasForeignKey("SanatoriumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sanatorium");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.Review", b =>
                {
                    b.HasOne("HousingReservation.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousingReservation.Domain.Entities.Sanatorium", "Sanatorium")
                        .WithMany("Reviews")
                        .HasForeignKey("SanatoriumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Sanatorium");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.Room", b =>
                {
                    b.HasOne("HousingReservation.Domain.Entities.BathroomType", "BathroomType")
                        .WithMany()
                        .HasForeignKey("BathroomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousingReservation.Domain.Entities.RoomGroup", "Group")
                        .WithMany("Rooms")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousingReservation.Domain.Entities.MealType", "MealType")
                        .WithMany()
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousingReservation.Domain.Entities.Sanatorium", "Sanatorium")
                        .WithMany("Rooms")
                        .HasForeignKey("SanatoriumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BathroomType");

                    b.Navigation("Group");

                    b.Navigation("MealType");

                    b.Navigation("Sanatorium");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.RoomAttribute", b =>
                {
                    b.HasOne("HousingReservation.Domain.Entities.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousingReservation.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.RoomReservation", b =>
                {
                    b.HasOne("HousingReservation.Domain.Entities.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousingReservation.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.Sanatorium", b =>
                {
                    b.HasOne("HousingReservation.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.SanatoriumAttribute", b =>
                {
                    b.HasOne("HousingReservation.Domain.Entities.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousingReservation.Domain.Entities.Sanatorium", "Sanatorium")
                        .WithMany("SanatoriumAttributes")
                        .HasForeignKey("SanatoriumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Sanatorium");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.SanatoriumPlace", b =>
                {
                    b.HasOne("HousingReservation.Domain.Entities.Place", "Place")
                        .WithMany("SanatoriumPlaces")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousingReservation.Domain.Entities.Sanatorium", "Sanatorium")
                        .WithMany("SanatoriumPlaces")
                        .HasForeignKey("SanatoriumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("Sanatorium");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.TourAgency", b =>
                {
                    b.HasOne("HousingReservation.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.TourBooking", b =>
                {
                    b.HasOne("HousingReservation.Domain.Entities.Tour", "Tour")
                        .WithMany("TourBookings")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousingReservation.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.AttributeGroup", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.Place", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("SanatoriumPlaces");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.PromoBlock", b =>
                {
                    b.Navigation("PromoBlockItems");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.Room", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Photos");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.RoomGroup", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.Sanatorium", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Photos");

                    b.Navigation("Reviews");

                    b.Navigation("Rooms");

                    b.Navigation("SanatoriumAttributes");

                    b.Navigation("SanatoriumPlaces");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.Tour", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("TourBookings");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.TourAgency", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("HousingReservation.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
